// <auto-generated />
namespace Biblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_obra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_obra));
        
        string IMigrationMetadata.Id
        {
            get { return "201607070110479_Update_obra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
